package EdoWorld::Model::EdoWDB2;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'EdoWDB2::Schema',
    
    connect_info => {
        dsn => 'dbi:mysql:database=test:host=localhost',
        user => 'root',
        password => 'ogtfu2ec',
    }
);

=head1 NAME

EdoWorld::Model::EdoWDB2 - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<EdoWorld>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<EdoWDB2::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.48

=head1 AUTHOR

root

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
